version: '3.1'

services:
  app:
    image: jenkins/jenkins:lts-jdk11
    restart: always
    environment:
      JAVA_OPTS: -Dhudson.footerURL=http://localhost
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
    - ./jdata:/var/jenkins_home