---
- name: Install dependencies for PostgreSQL
  apt: name={{ item }} state=latest update_cache=yes force_apt_get=yes
  with_items:
  - bash
  - openssl
  - libssl-dev
  - libssl-doc

- name: Install PostgreSQL 
  apt: name={{ item }} update_cache=yes state=present
  with_items:
  - postgresql
  - postgresql-contrib
  - libpq-dev
  - python3-psycopg2

- name: Ensure the PostgreSQL service is running
  service: name=postgresql state=started enabled=yes

- name: Create /opt/postgres directory if it does not exist
  file:
    path: /opt/postgres
    state: directory
    mode: '0755'

- name: Copy psql script into /opt/postgres
  template:
    src: psql.sh.j2
    dest: /opt/postgres/psql.sh
    owner: root
    group: root
    mode: '0744'
