apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: tc-agent
  annotations:
    description: TeamCity agent template
objects:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: tc-agent
    name: tc-agent
  spec:
    replicas: 1
    selector:
      app: tc-agent
      deploymentconfig: tc-agent
    strategy:
      activeDeadlineSeconds: 21600
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Recreate
    template:
      metadata:
        labels:
          app: tc-agent
          deploymentconfig: tc-agent
      spec:
        containers:
          - image: ${IMAGE}
            imagePullPolicy: Always
            name: tc-agent
            env:
            - name: SERVER_URL
              value: ${SERVER_URL}
            - name: AGENT_NAME
              value: Agent47
            - name: OWN_PORT
              value: "9090"
            - name: DOCKER_IN_DOCKER
              value: start
            ports:
              - containerPort: 9090
                protocol: TCP
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext:
          fsGroup: 1000
          runAsUser: 1000
        terminationGracePeriodSeconds: 30
    test: false
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: tc-agent
    name: tc-agent
  spec:
    ports:
      - name: 9090-tcp
        port: 9090
        protocol: TCP
        targetPort: 9090
    selector:
      deploymentconfig: tc-agent
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
parameters:
  - name: IMAGE
    diplayName: IMAGE
    description: IMAGE jetbrains/teamcity-agent docker image
    value: jetbrains/teamcity-agent
    required: true
  - name: SERVER_URL
    diplayName: SERVER_URL
    description: SERVER_URL jetbrains/teamcity-server url
    value:
    required: true